ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super_admin": ["*"],
    "quiz_admin": [
        "quiz:list", "quiz:write", "quiz:import",
        "quiz_content_edit", "quiz_content_publish", "quiz_library_manage",
        "course_quiz_bind",
        "course_assignment_manage",
    ],
    "cert_admin": [
        "content:read",
        "content:list",
        "content:write",
        "user:list",
        "user:write",
        "order:list",
        "h3c:batch_manage",
        "h3c:review",
        "h3c:export",
        "h3c:refund",
        "h3c:order_close",
    ],
    "course_admin": [
        "quiz:list",
        "course:read",
        "course:write",
        "course:publish",
        "course_assignment_manage",
        "course_assignment_review",
    ],
}
