"""restructure user tables

Revision ID: 3fd0076eb0ce
Revises: a6e6c372d20f
Create Date: 2026-06-10 03:22:19.353666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fd0076eb0ce'
down_revision: Union[str, Sequence[str], None] = 'a6e6c372d20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_enterprise',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_enterprise_status'), 'user_enterprise', ['status'], unique=False)
    op.create_index(op.f('ix_user_enterprise_user_id'), 'user_enterprise', ['user_id'], unique=True)
    op.create_table('user_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('user_realname',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=16), nullable=False),
    sa.Column('real_name', sa.String(length=64), nullable=False),
    sa.Column('id_card_number', sa.String(length=18), nullable=False),
    sa.Column('id_card_front_oss', sa.String(length=512), nullable=True),
    sa.Column('id_card_back_oss', sa.String(length=512), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('census_register', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_realname_id_card_number'), 'user_realname', ['id_card_number'], unique=False)
    op.create_index(op.f('ix_user_realname_status'), 'user_realname', ['status'], unique=False)
    op.create_index(op.f('ix_user_realname_user_id'), 'user_realname', ['user_id'], unique=True)
    op.create_table('user_student',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=32), nullable=False),
    sa.Column('school', sa.String(length=128), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=False),
    sa.Column('student_card_oss', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_student_status'), 'user_student', ['status'], unique=False)
    op.create_index(op.f('ix_user_student_user_id'), 'user_student', ['user_id'], unique=True)
    op.drop_index(op.f('ix_user_identity_id_card_number'), table_name='user_identity')
    op.drop_index(op.f('ix_user_identity_status'), table_name='user_identity')
    op.drop_index(op.f('ix_user_identity_user_id'), table_name='user_identity')
    op.drop_table('user_identity')
    op.add_column('user', sa.Column('level2_edit_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('level2_edit_reset_at', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level2_edit_reset_at')
    op.drop_column('user', 'level2_edit_count')
    op.create_table('user_identity',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('real_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('id_card_number', sa.VARCHAR(length=18), autoincrement=False, nullable=True),
    sa.Column('id_card_front_oss', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('id_card_back_oss', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('student_card_oss', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'verified'::character varying"), autoincrement=False, nullable=False),
    sa.Column('verified_at', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('edit_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=16), server_default=sa.text("'enterprise'::character varying"), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('school', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_identity_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_identity_pkey'))
    )
    op.create_index(op.f('ix_user_identity_user_id'), 'user_identity', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_identity_status'), 'user_identity', ['status'], unique=False)
    op.create_index(op.f('ix_user_identity_id_card_number'), 'user_identity', ['id_card_number'], unique=False)
    op.drop_index(op.f('ix_user_student_user_id'), table_name='user_student')
    op.drop_index(op.f('ix_user_student_status'), table_name='user_student')
    op.drop_table('user_student')
    op.drop_index(op.f('ix_user_realname_user_id'), table_name='user_realname')
    op.drop_index(op.f('ix_user_realname_status'), table_name='user_realname')
    op.drop_index(op.f('ix_user_realname_id_card_number'), table_name='user_realname')
    op.drop_table('user_realname')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_enterprise_user_id'), table_name='user_enterprise')
    op.drop_index(op.f('ix_user_enterprise_status'), table_name='user_enterprise')
    op.drop_table('user_enterprise')
    # ### end Alembic commands ###
