"""add_job_application_and_activity_reminder_tables

Revision ID: 570fce4c60fc
Revises: merge_heads_001
Create Date: 2026-06-04 00:45:06.125820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570fce4c60fc'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import logging

_log = logging.getLogger(__name__)


def _safe_create_index(index_name, table, columns, **kw):
    """幂等创建索引"""
    try:
        op.create_index(index_name, table, columns, **kw)
    except Exception:
        pass


def _has_constraint(table_name, constraint_name):
    """检查约束是否存在"""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM pg_constraint WHERE conname = :name AND conrelid = :table::regclass"
        ),
        {"name": constraint_name, "table": table_name},
    )
    return result.fetchone() is not None


def _has_index(index_name, table_name):
    """检查索引是否存在"""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :name AND tablename = :table"
        ),
        {"name": index_name, "table": table_name},
    )
    return result.fetchone() is not None


def _safe_drop_constraint(constraint_name, table_name, **kw):
    """幂等删除约束 — 先检查再删除"""
    if _has_constraint(table_name, constraint_name):
        op.drop_constraint(constraint_name, table_name, **kw)


def _safe_drop_index(index_name, **kw):
    """幂等删除索引 — 先检查再删除"""
    table_name = kw.get('table_name', '')
    if table_name and _has_index(index_name, table_name):
        op.drop_index(index_name, **kw)
    else:
        try:
            op.drop_index(index_name, **kw)
        except Exception:
            pass


def _safe_alter_column(table, column, **kw):
    """幂等修改列 — 简单 try/except（alter 不回滚事务? 用检查）"""
    try:
        op.alter_column(table, column, **kw)
    except Exception:
        # alter column 失败也可能中止事务，回滚
        op.get_bind().execute(sa.text("ROLLBACK"))
        op.get_bind().execute(sa.text("BEGIN"))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = inspector.get_table_names()
    if 'activity' not in existing:
        op.create_table('activity',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if 'job' not in existing:
        op.create_table('job',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('company', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('salary_range', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if 'activity_registration' not in existing:
        op.create_table('activity_registration',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_activity_registration_activity_id'), 'activity_registration', ['activity_id'], unique=False)
    _safe_create_index(op.f('ix_activity_registration_user_id'), 'activity_registration', ['user_id'], unique=False)
    if 'activity_reminder' not in existing:
        op.create_table('activity_reminder',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('reminded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_activity_reminder_activity_id'), 'activity_reminder', ['activity_id'], unique=False)
    _safe_create_index(op.f('ix_activity_reminder_user_id'), 'activity_reminder', ['user_id'], unique=False)
    if 'collection' not in existing:
        op.create_table('collection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False, comment='收藏类型: course / material'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标资源 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_collection_user_id'), 'collection', ['user_id'], unique=False)
    if 'job_application' not in existing:
        op.create_table('job_application',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_job_application_job_id'), 'job_application', ['job_id'], unique=False)
    _safe_create_index(op.f('ix_job_application_user_id'), 'job_application', ['user_id'], unique=False)
    if 'share' not in existing:
        op.create_table('share',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _safe_create_index(op.f('ix_share_code'), 'share', ['code'], unique=True)
    _safe_create_index(op.f('ix_share_user_id'), 'share', ['user_id'], unique=False)
    _safe_drop_constraint(op.f('admin_user_username_key'), 'admin_user', type_='unique')
    _safe_alter_column('certification', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    _safe_drop_constraint(op.f('deleted_openid_openid_key'), 'deleted_openid', type_='unique')
    _safe_drop_index(op.f('ix_deleted_openid_openid'), table_name='deleted_openid')
    _safe_create_index(op.f('ix_deleted_openid_openid'), 'deleted_openid', ['openid'], unique=True)
    _safe_drop_index(op.f('uq_quiz_checkin_user_date'), table_name='quiz_checkin')
    _safe_drop_index(op.f('uq_quiz_record_user_question'), table_name='quiz_record')
    _safe_drop_constraint(op.f('user_identity_user_id_key'), 'user_identity', type_='unique')
    _safe_drop_index(op.f('ix_user_identity_user_id'), table_name='user_identity')
    _safe_create_index(op.f('ix_user_identity_user_id'), 'user_identity', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _safe_drop_index(op.f('ix_user_identity_user_id'), table_name='user_identity')
    _safe_create_index(op.f('ix_user_identity_user_id'), 'user_identity', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_identity_user_id_key'), 'user_identity', ['user_id'], postgresql_nulls_not_distinct=False)
    _safe_create_index(op.f('uq_quiz_record_user_question'), 'quiz_record', ['user_id', 'question_id'], unique=True)
    _safe_create_index(op.f('uq_quiz_checkin_user_date'), 'quiz_checkin', ['user_id', 'checkin_date'], unique=True)
    _safe_drop_index(op.f('ix_deleted_openid_openid'), table_name='deleted_openid')
    _safe_create_index(op.f('ix_deleted_openid_openid'), 'deleted_openid', ['openid'], unique=False)
    op.create_unique_constraint(op.f('deleted_openid_openid_key'), 'deleted_openid', ['openid'], postgresql_nulls_not_distinct=False)
    _safe_alter_column('certification', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.create_unique_constraint(op.f('admin_user_username_key'), 'admin_user', ['username'], postgresql_nulls_not_distinct=False)
    _safe_drop_index(op.f('ix_share_user_id'), table_name='share')
    _safe_drop_index(op.f('ix_share_code'), table_name='share')
    op.drop_table('share')
    _safe_drop_index(op.f('ix_job_application_user_id'), table_name='job_application')
    _safe_drop_index(op.f('ix_job_application_job_id'), table_name='job_application')
    op.drop_table('job_application')
    _safe_drop_index(op.f('ix_collection_user_id'), table_name='collection')
    op.drop_table('collection')
    _safe_drop_index(op.f('ix_activity_reminder_user_id'), table_name='activity_reminder')
    _safe_drop_index(op.f('ix_activity_reminder_activity_id'), table_name='activity_reminder')
    op.drop_table('activity_reminder')
    _safe_drop_index(op.f('ix_activity_registration_user_id'), table_name='activity_registration')
    _safe_drop_index(op.f('ix_activity_registration_activity_id'), table_name='activity_registration')
    op.drop_table('activity_registration')
    op.drop_table('job')
    op.drop_table('activity')
    # ### end Alembic commands ###
