"""add banner target_type target_id fields

Revision ID: 712f3910f7f1
Revises: c0b48b083f82
Create Date: 2026-06-08 23:24:40.065890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712f3910f7f1'
down_revision: Union[str, Sequence[str], None] = 'c0b48b083f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('target_type', sa.String(length=32), nullable=True, comment='跳转资源类型: cert/course/activity/zone/url'))
    op.add_column('banner', sa.Column('target_id', sa.Integer(), nullable=True, comment='跳转资源 ID，target_type=url 时为空'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banner', 'target_id')
    op.drop_column('banner', 'target_type')
    # ### end Alembic commands ###
