"""make user_identity fields nullable

Revision ID: a6e6c372d20f
Revises: 712f3910f7f1
Create Date: 2026-06-09 23:10:59.179498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e6c372d20f'
down_revision: Union[str, Sequence[str], None] = '712f3910f7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deleted')
    op.alter_column('user_identity', 'user_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'enterprise'::character varying"))
    op.alter_column('user_identity', 'real_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user_identity', 'id_card_number',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_identity', 'id_card_number',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)
    op.alter_column('user_identity', 'real_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('user_identity', 'user_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'enterprise'::character varying"))
    op.add_column('user', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
