"""add_extra_data_and_attachments_to_order

Revision ID: b0a64a214cb4
Revises: 570fce4c60fc
Create Date: 2026-06-04 01:32:39.244859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a64a214cb4'
down_revision: Union[str, Sequence[str], None] = '570fce4c60fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('extra_data', sa.JSON(), nullable=True, comment='按 cert_type 存的差异化报名数据'))
    op.add_column('order', sa.Column('attachments', sa.JSON(), nullable=True, comment='上传材料 URL 列表'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'attachments')
    op.drop_column('order', 'extra_data')
    # ### end Alembic commands ###
