"""add_profile_fields_to_user_identity

Revision ID: f8e586b20e8c
Revises: b0a64a214cb4
Create Date: 2026-06-04 01:56:03.759723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e586b20e8c'
down_revision: Union[str, Sequence[str], None] = 'b0a64a214cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_identity', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('user_identity', sa.Column('education', sa.String(length=32), nullable=True))
    op.add_column('user_identity', sa.Column('gender', sa.String(length=8), nullable=True))
    op.add_column('user_identity', sa.Column('school', sa.String(length=128), nullable=True))
    op.add_column('user_identity', sa.Column('major', sa.String(length=128), nullable=True))
    op.add_column('user_identity', sa.Column('organization', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identity', 'organization')
    op.drop_column('user_identity', 'major')
    op.drop_column('user_identity', 'school')
    op.drop_column('user_identity', 'gender')
    op.drop_column('user_identity', 'education')
    op.drop_column('user_identity', 'email')
    # ### end Alembic commands ###
