from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    text,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.adapter.database import Base, TimestampMixin


class PointsMallItem(Base, TimestampMixin):
    """Admin-managed coupon template that users can redeem with points."""

    __tablename__ = "points_mall_item"
    __table_args__ = (
        CheckConstraint(
            "discount_type IN ('fixed', 'percent')",
            name="ck_pm_item_discount_type",
        ),
        CheckConstraint(
            "discount_value > 0",
            name="ck_pm_item_discount_positive",
        ),
        CheckConstraint(
            "scope_type IN ('global', 'category', 'product')",
            name="ck_pm_item_scope_type",
        ),
        CheckConstraint(
            "validity_type IN ('days', 'fixed_date')",
            name="ck_pm_item_validity_type",
        ),
        CheckConstraint(
            "points_cost > 0",
            name="ck_pm_item_points_positive",
        ),
        CheckConstraint(
            "total_stock >= 0 AND total_redeemed >= 0 AND per_user_limit >= 0",
            name="ck_pm_item_limits_nonnegative",
        ),
        CheckConstraint(
            "min_order_amount_cents >= 0",
            name="ck_pm_item_min_order_nonnegative",
        ),
        Index("ix_pm_item_active_sort", "is_active", "sort_order"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str | None] = mapped_column(String(256))

    discount_type: Mapped[str] = mapped_column(String(16), nullable=False)
    discount_value: Mapped[int] = mapped_column(Integer, nullable=False)

    scope_type: Mapped[str] = mapped_column(
        String(16), nullable=False, default="global", server_default="global"
    )
    scope_value: Mapped[str | None] = mapped_column(String(64))

    min_order_amount_cents: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )

    points_cost: Mapped[int] = mapped_column(Integer, nullable=False)

    total_stock: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    total_redeemed: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )
    per_user_limit: Mapped[int] = mapped_column(
        Integer, nullable=False, default=1, server_default="1"
    )

    validity_type: Mapped[str] = mapped_column(
        String(16), nullable=False, default="days", server_default="days"
    )
    validity_days: Mapped[int | None] = mapped_column(Integer)
    valid_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default="true"
    )
    sort_order: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default="0"
    )


class PointsMallRedemption(Base, TimestampMixin):
    """A user-owned coupon generated by redeeming points."""

    __tablename__ = "points_mall_redemption"
    __table_args__ = (
        CheckConstraint("points_spent > 0", name="ck_pm_redemption_points_positive"),
        CheckConstraint(
            "discount_type IN ('fixed', 'percent')",
            name="ck_pm_redemption_discount_type",
        ),
        Index("ix_pm_redemption_user", "user_id", "status"),
        Index("ix_pm_redemption_item", "item_id"),
        Index("uq_pm_redemption_order", "order_id", unique=True, postgresql_where=text("order_id IS NOT NULL")),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("user.id", ondelete="CASCADE"), nullable=False, index=True
    )
    item_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("points_mall_item.id", ondelete="RESTRICT"),
        nullable=False,
    )

    points_spent: Mapped[int] = mapped_column(Integer, nullable=False)
    coupon_code: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)

    # Snapshot of the coupon definition at redemption time
    name_snapshot: Mapped[str] = mapped_column(String(128), nullable=False)
    discount_type: Mapped[str] = mapped_column(String(16), nullable=False)
    discount_value: Mapped[int] = mapped_column(Integer, nullable=False)
    scope_type: Mapped[str] = mapped_column(String(16), nullable=False)
    scope_value: Mapped[str | None] = mapped_column(String(64))
    min_order_amount_cents: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="unused", server_default="unused"
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    order_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("order.id", ondelete="SET NULL")
    )
