from app.domain.content.src.index import (
    Activity, ActivityRegistration, ActivityReminder,
    Agreement, Ticket, Zone,
)
from app.domain.certification.src.index import (
    Certification,
    CompetitionReg,
    Course,
    CourseAuditLog,
    CourseCategory,
    CourseChapter,
    CourseEnrollment,
    CourseEntitlementJob,
    CourseEntitlementJobItem,
    Job,
    JobApplication,
    UserChapterProgress,
)
from app.domain.community.src.index import (
    Collection,
    Conversation,
    QuickQuestion,
    QuizAdminAuditLog,
    QuizCategory,
    QuizCheckin,
    QuizCollection,
    QuizCourseLibraryBinding,
    QuizExam,
    QuizExamAnswer,
    QuizExamQuestion,
    QuizImportJob,
    QuizImportError,
    QuizKnowledgePoint,
    QuizLegacyMigrationMap,
    QuizLibrary,
    QuizLibraryEntitlement,
    QuizMigrationIssue,
    QuizModule,
    QuizPracticeAttempt,
    QuizPracticeSession,
    QuizPracticeSessionQuestion,
    QuizQuestion,
    QuizQuestionRevision,
    QuizQuestionRevisionStats,
    QuizQuestionStats,
    QuizUserStats,
    QuizWrongItem,
    Share,
)
from app.domain.plan.src.index import Plan
from app.domain.order.src.index import Coupon, Inventory, InventoryRecord, Order, PriceConfig, UserCoupon
from app.domain.user.src.index import (
    AdminPasswordHistory, AdminSecurityAudit, AdminUser,
    DeletedIdentityHash, DeletedOpenid, PointsHistory,
    User, UserEnterprise, UserPoints, UserProfile, UserRealname, UserStudent, ADMIN_ROLES,
)
from app.domain.renshe.src.index import (
    RensheApplication,
    RensheApplicationVersion,
    RensheAuditLog,
    RensheCleanupRun,
    RensheExportItem,
    RensheExportJob,
    RensheExportVolume,
    RensheMaterial,
    RensheRefundRequest,
    RensheReview,
    RensheReviewCorrection,
)
from app.domain.h3c.src.index import (
    H3cExamBatch,
    H3cExportItem,
    H3cExportJob,
    H3cMaterial,
    H3cRefundRequest,
    H3cRegistration,
    H3cReview,
)
from app.models.deployment_acceptance import (
    DeploymentAcceptance,
    DeploymentAcceptanceEvent,
)

from app.models.cert_product import CertProduct

__all__ = [
    "Activity",
    "ActivityRegistration",
    "ActivityReminder",
    "ADMIN_ROLES",
    "AdminPasswordHistory",
    "AdminSecurityAudit",
    "AdminUser",
    "Agreement",
    "Certification",
    "Collection",
    "CompetitionReg",
    "Conversation",
    "Coupon",
    "Course",
    "CourseAuditLog",
    "CourseCategory",
    "CourseChapter",
    "CourseEnrollment",
    "CourseEntitlementJob",
    "CourseEntitlementJobItem",
    "DeletedOpenid",
    "DeletedIdentityHash",
    "DeploymentAcceptance",
    "DeploymentAcceptanceEvent",
    "CertProduct",
    "Inventory",
    "InventoryRecord",
    "Job",
    "JobApplication",
    "Order",
    "Plan",
    "PointsHistory",
    "PriceConfig",
    "QuickQuestion",
    "QuizAdminAuditLog",
    "QuizCategory",
    "QuizCheckin",
    "QuizCollection",
    "QuizCourseLibraryBinding",
    "QuizExam",
    "QuizExamAnswer",
    "QuizExamQuestion",
    "QuizImportJob",
    "QuizImportError",
    "QuizKnowledgePoint",
    "QuizLegacyMigrationMap",
    "QuizLibrary",
    "QuizLibraryEntitlement",
    "QuizMigrationIssue",
    "QuizModule",
    "QuizPracticeAttempt",
    "QuizPracticeSession",
    "QuizPracticeSessionQuestion",
    "QuizQuestion",
    "QuizQuestionRevision",
    "QuizQuestionRevisionStats",
    "QuizQuestionStats",
    "QuizUserStats",
    "QuizWrongItem",
    "Share",
    "Ticket",
    "User",
    "UserChapterProgress",
    "UserEnterprise",
    "UserProfile",
    "UserRealname",
    "UserStudent",
    "UserCoupon",
    "UserPoints",
    "Zone",
    "RensheApplication",
    "RensheApplicationVersion",
    "RensheAuditLog",
    "RensheCleanupRun",
    "RensheExportItem",
    "RensheExportJob",
    "RensheExportVolume",
    "RensheMaterial",
    "RensheRefundRequest",
    "RensheReview",
    "RensheReviewCorrection",
    "H3cExamBatch",
    "H3cExportItem",
    "H3cExportJob",
    "H3cMaterial",
    "H3cRefundRequest",
    "H3cRegistration",
    "H3cReview",
]
